# Generated by Django 3.0.4 on 2020-03-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articleId',
            new_name='article',
        ),
    ]
